import React, { useState } from 'react';
import {
  Copy,
  Printer,
  Edit3,
  CheckCircle2,
  FileCheck,
  SlidersHorizontal,
  RotateCcw,
  Sparkles,
  FileText
} from 'lucide-react';
import { Bed } from '../../types/bed';
import {
  generateHospitalEvolutionText,
  generateDefaultHda,
  generateDefaultHdaBody,
  extractHdaBody
} from '../../utils/evolutionGenerator';
import { BloodPressureInput } from '../common/BloodPressureInput';
import { ObstetricHistoryInput } from '../common/ObstetricHistoryInput';
import { getBedBP } from '../../utils/bpAnalyzer';

interface EvolutionTabProps {
  bed: Bed;
  onUpdateBed?: (updates: Partial<Bed>) => void;
  onShowToast: (msg: string) => void;
  onNavigateToDischarge: () => void;
}

export const EvolutionTab: React.FC<EvolutionTabProps> = ({
  bed,
  onUpdateBed,
  onShowToast,
  onNavigateToDischarge
}) => {
  const generatedText = generateHospitalEvolutionText(bed);
  const [customText, setCustomText] = useState<string | null>(null);
  const [isDirectEditing, setIsDirectEditing] = useState(false);
  const [showForm, setShowForm] = useState(true);

  const displayText = customText !== null ? customText : generatedText;

  const currentParidade = bed.obstetricHistory || bed.data?.obstetricHistory || 'G01P00(n00 C 00)A00';
  const autoGeneratedBody = generateDefaultHdaBody(bed);
  const currentHdaBody = extractHdaBody(
    bed.hda !== undefined && bed.hda !== '' ? bed.hda : autoGeneratedBody,
    currentParidade
  );

  const handleGenerateAutoHda = () => {
    const body = generateDefaultHdaBody(bed);
    updateField('hda', body);
    onShowToast('HDA gerada e mantida no campo com sucesso!');
  };

  const handleHdaChange = (val: string) => {
    const cleaned = extractHdaBody(val, currentParidade);
    updateField('hda', cleaned);
  };

  const copyToClipboard = () => {
    if (!navigator?.clipboard) {
      onShowToast('Área de transferência indisponível');
      return;
    }
    navigator.clipboard
      .writeText(displayText)
      .then(() => {
        onShowToast('Evolução copiada com sucesso para o prontuário!');
      })
      .catch(() => {
        onShowToast('Erro ao copiar.');
      });
  };

  const handleResetToAuto = () => {
    setCustomText(null);
    setIsDirectEditing(false);
    onShowToast('Texto restaurado para o formato gerado automaticamente.');
  };

  const updateField = (field: keyof Bed, value: any) => {
    if (onUpdateBed) {
      onUpdateBed({ [field]: value });
      // If user was using custom text, reset it so live generator updates
      if (customText !== null) {
        setCustomText(null);
      }
    }
  };

  const quickAppendConduta = (line: string) => {
    const current = bed.condutaText || '';
    const updated = current.trim() ? `${current.trim()}\n${line}` : line;
    updateField('condutaText', updated);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-4">
      {/* Top Banner & Control Bar */}
      <div className="bg-white rounded-3xl border border-slate-200 p-4 sm:p-5 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-bold tracking-wider uppercase px-2.5 py-0.5 rounded-full bg-purple-100 text-purple-800 border border-purple-200">
                Modelo Oficial de Evolução Médica (evolucao.txt)
              </span>
              <span className="text-[10px] font-bold text-slate-500 bg-slate-100 px-2 py-0.5 rounded-full">
                Leito {bed.label}
              </span>
            </div>
            <h2 className="text-base sm:text-lg font-bold text-slate-900 mt-1">
              Evolução Médica - {bed.patientName} ({bed.diagnosis || 'Sem diagnóstico'})
            </h2>
            <p className="text-xs text-slate-500">
              Estruturada rigorosamente conforme o modelo: HDA, COMORBIDADES, MUC, ALERGIA, EVOLUÇÃO, EXAME FÍSICO, SSVV, EXAMES COMPLEMENTARES, HD e CONDUTA.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={() => setShowForm(!showForm)}
              className={`px-3 py-2 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer border ${
                showForm
                  ? 'bg-purple-50 text-purple-700 border-purple-200'
                  : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
              }`}
            >
              <SlidersHorizontal className="w-3.5 h-3.5" />
              <span>{showForm ? 'Ocultar Campos' : 'Ajustar Campos'}</span>
            </button>

            <button
              onClick={() => setIsDirectEditing(!isDirectEditing)}
              className={`px-3 py-2 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer border ${
                isDirectEditing
                  ? 'bg-amber-50 text-amber-800 border-amber-200'
                  : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
              }`}
            >
              <Edit3 className="w-3.5 h-3.5" />
              <span>{isDirectEditing ? 'Modo Visualização' : 'Edição Livre'}</span>
            </button>

            {customText !== null && (
              <button
                onClick={handleResetToAuto}
                className="px-3 py-2 rounded-xl text-xs font-semibold text-rose-700 bg-rose-50 border border-rose-200 hover:bg-rose-100 transition-all flex items-center gap-1 cursor-pointer"
                title="Descartar edições livres e voltar ao gerador automático"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Restaurar Auto</span>
              </button>
            )}

            <button
              onClick={copyToClipboard}
              className="w-full sm:w-auto px-4 py-2.5 sm:py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 shadow-xs transition-all active:scale-95 cursor-pointer order-first sm:order-none"
            >
              <Copy className="w-3.5 h-3.5" />
              <span>Copiar Evolução</span>
            </button>

            <button
              onClick={() => window.print()}
              className="p-2 border border-slate-200 rounded-xl text-slate-600 hover:bg-slate-50 transition-all text-xs cursor-pointer"
              title="Imprimir Evolução"
            >
              <Printer className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Structured Fields Quick Editor */}
        {showForm && onUpdateBed && (
          <div className="mt-4 pt-3 border-t border-slate-100 bg-slate-50/70 p-4 rounded-2xl border border-slate-200">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider">
                <Sparkles className="w-3.5 h-3.5 text-purple-600" />
                Preenchimento Rápido dos Campos da Evolução
              </span>
              <span className="text-[11px] text-slate-400">
                Os dados digitados aqui atualizam o texto formatado em tempo real.
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
              {/* Comorbidades */}
              <div>
                <label className="text-[11px] font-bold text-slate-600 uppercase block mb-1">
                  COMORBIDADES:
                </label>
                <input
                  type="text"
                  value={bed.comorbidades ?? 'NEGA'}
                  onChange={(e) => updateField('comorbidades', e.target.value)}
                  placeholder="NEGA ou HAS, DMG, etc."
                  className="w-full bg-white border border-slate-200 rounded-xl px-2.5 py-1.5 text-xs text-slate-800 focus:outline-none focus:border-purple-500 font-semibold"
                />
                <div className="flex gap-1 mt-1">
                  {['NEGA', 'HAS', 'DMG', 'OBESIDADE'].map((tag) => (
                    <button
                      key={tag}
                      type="button"
                      onClick={() => updateField('comorbidades', tag)}
                      className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer"
                    >
                      {tag}
                    </button>
                  ))}
                </div>
              </div>

              {/* MUC */}
              <div>
                <label className="text-[11px] font-bold text-slate-600 uppercase block mb-1">
                  MUC (Uso Contínuo):
                </label>
                <input
                  type="text"
                  value={bed.muc ?? 'NEGA'}
                  onChange={(e) => updateField('muc', e.target.value)}
                  placeholder="NEGA ou Sulfato Ferroso, etc."
                  className="w-full bg-white border border-slate-200 rounded-xl px-2.5 py-1.5 text-xs text-slate-800 focus:outline-none focus:border-purple-500 font-semibold"
                />
                <div className="flex gap-1 mt-1">
                  {['NEGA', 'SULFATO FERROSO', 'METILDOPA'].map((tag) => (
                    <button
                      key={tag}
                      type="button"
                      onClick={() => updateField('muc', tag)}
                      className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer"
                    >
                      {tag}
                    </button>
                  ))}
                </div>
              </div>

              {/* ALERGIA */}
              <div>
                <label className="text-[11px] font-bold text-slate-600 uppercase block mb-1">
                  ALERGIA:
                </label>
                <input
                  type="text"
                  value={bed.alergias ?? 'NEGA ALERGIA'}
                  onChange={(e) => updateField('alergias', e.target.value)}
                  placeholder="NEGA ALERGIA ou DIPIRONA..."
                  className="w-full bg-white border border-slate-200 rounded-xl px-2.5 py-1.5 text-xs text-slate-800 focus:outline-none focus:border-purple-500 font-semibold"
                />
                <div className="flex gap-1 mt-1">
                  {['NEGA ALERGIA', 'DIPIRONA', 'PENICILINA'].map((tag) => (
                    <button
                      key={tag}
                      type="button"
                      onClick={() => updateField('alergias', tag.includes('NEGA') ? tag : `ALERGIA: ${tag}`)}
                      className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer"
                    >
                      {tag}
                    </button>
                  ))}
                </div>
              </div>

              {/* Dias de Internação */}
              <div>
                <label className="text-[11px] font-bold text-slate-600 uppercase block mb-1">
                  Dias de Internação:
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="number"
                    min="1"
                    max="90"
                    value={bed.internmentDays ?? 1}
                    onChange={(e) => updateField('internmentDays', parseInt(e.target.value) || 1)}
                    className="w-20 bg-white border border-slate-200 rounded-xl px-2.5 py-1.5 text-xs text-slate-800 text-center font-bold focus:outline-none focus:border-purple-500"
                  />
                  <span className="text-xs text-slate-500 font-medium">° dia de enfermaria</span>
                </div>
              </div>

              {/* Queixas Adicionais da Paciente (Span 2) */}
              <div className="md:col-span-2">
                <label className="text-[11px] font-bold text-slate-600 uppercase block mb-1">
                  Queixas Adicionais da Paciente (Alimenta o campo EVOLUÇÃO):
                </label>
                <input
                  type="text"
                  value={bed.queixasAdicionais ?? ''}
                  onChange={(e) => updateField('queixasAdicionais', e.target.value)}
                  placeholder="Ex: Refere cefaleia holocraniana leve após deambulação; relata dor lombar persistente..."
                  className="w-full bg-white border border-slate-200 rounded-xl px-2.5 py-1.5 text-xs text-slate-800 focus:outline-none focus:border-purple-500 font-semibold"
                />
              </div>

              {/* História Obstétrica / Paridade (Span 2) */}
              <div className="md:col-span-2">
                <ObstetricHistoryInput
                  value={bed.obstetricHistory || 'G01P00(n00 C 00)A00'}
                  onChange={(val) => updateField('obstetricHistory', val)}
                  label="Paridade Obstétrica (G P n C A):"
                />
              </div>

              {/* Pressão Arterial Auto-detectada (Span 2) */}
              <div className="md:col-span-2">
                <BloodPressureInput
                  value={getBedBP(bed)}
                  onChange={(val) => {
                    updateField('bloodPressure', val);
                    if (onUpdateBed) {
                      onUpdateBed({
                        bloodPressure: val,
                        data: { ...(bed.data || {}), bloodPressure: val, bpValue: val }
                      });
                    }
                  }}
                  label="Pressão Arterial (Auto-Detectada para SSVV):"
                  showQuickChips={true}
                />
              </div>

              {/* HDA (Span 2) */}
              <div className="md:col-span-2 space-y-1.5">
                <div className="flex flex-wrap items-center justify-between gap-1.5 mb-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <label className="text-[11px] font-bold text-slate-700 uppercase block">
                      HDA (História da Doença Atual):
                    </label>
                  </div>

                  <button
                    type="button"
                    onClick={handleGenerateAutoHda}
                    className="text-[10px] font-bold text-purple-700 hover:text-purple-900 bg-purple-50 hover:bg-purple-100 border border-purple-200 px-2.5 py-1 rounded-lg flex items-center gap-1.5 transition-all cursor-pointer shadow-2xs active:scale-95"
                    title="Preenche o campo abaixo com o texto gerado a partir dos dados do leito"
                  >
                    <Sparkles className="w-3.5 h-3.5 text-purple-600" />
                    <span>Auto-Gerar HDA</span>
                  </button>
                </div>

                {/* Box com prefixo fixo inalterável + campo de digitação */}
                <div className="rounded-xl border border-slate-300 overflow-hidden focus-within:border-purple-500 focus-within:ring-2 focus-within:ring-purple-200/50 bg-white transition-all shadow-2xs">
                  <div className="bg-purple-50 border-b border-purple-100 px-3 py-1.5 text-xs font-mono font-bold text-purple-950 flex flex-wrap items-center justify-between gap-2 select-none">
                    <div className="flex items-center gap-2">
                      <span className="text-[9px] uppercase font-sans tracking-wider px-1.5 py-0.5 rounded bg-purple-200/90 text-purple-900 font-extrabold">
                        Parte Fixa Obrigatória
                      </span>
                      <span className="text-purple-950 font-bold font-mono">
                        HDA: PACIENTE {currentParidade}
                      </span>
                    </div>
                    <span className="text-[10px] font-sans text-purple-600 font-medium">
                      (Sempre fixo no início)
                    </span>
                  </div>

                  <textarea
                    rows={3}
                    value={currentHdaBody}
                    onChange={(e) => handleHdaChange(e.target.value)}
                    placeholder="EM 04/09/26 DE PÓS CESÁRIA, DEU ENTRADA AO SERVIÇO EM 18/09/2026, A CEFALEIA E DOR LOMBAR E PA ELEVADA DE 160X111MMHG. SENDO SULFATADA."
                    className="w-full p-2.5 text-xs text-slate-800 focus:outline-none font-mono leading-relaxed resize-y"
                  />
                </div>

                {/* Quick Presets for HDA */}
                <div className="flex flex-wrap items-center gap-1.5 pt-0.5">
                  <span className="text-[9px] text-slate-400 font-semibold uppercase">Modelos Rápidos:</span>
                  <button
                    type="button"
                    onClick={() => {
                      const bpVal = getBedBP(bed).toUpperCase().replace('/', 'X');
                      const txt = `EM ${bed.data?.deliveryDate || bed.admissionDate || '04/09/26'} DE PÓS CESÁRIA, DEU ENTRADA AO SERVIÇO EM ${bed.admissionDate || '18/09/2026'}, A CEFALEIA E DOR LOMBAR E PA ELEVADA DE ${bpVal}MMHG. SENDO SULFATADA.`;
                      updateField('hda', txt);
                      onShowToast('Modelo pós-cesárea inserido!');
                    }}
                    className="text-[9px] px-2 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer transition-colors"
                  >
                    Pós-Cesárea (Sulfatada)
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const txt = `EM ${bed.data?.deliveryDate || bed.admissionDate || 'RECENTE'} DE PÓS PARTO NORMAL, DEU ENTRADA AO SERVIÇO EM TRABALHO DE PARTO. EVOLUIU BEM, SEM QUEIXAS NO MOMENTO.`;
                      updateField('hda', txt);
                      onShowToast('Modelo pós-parto normal inserido!');
                    }}
                    className="text-[9px] px-2 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer transition-colors"
                  >
                    Pós-Parto Normal
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const txt = `GESTANTE COM IG DE ${bed.data?.gestationalAge || 32} SEMANAS, ADMITIDA POR AMEAÇA DE PARTO PREMATURO. NEGA PERDAS VAGINAIS NO MOMENTO.`;
                      updateField('hda', txt);
                      onShowToast('Modelo gestante TPP inserido!');
                    }}
                    className="text-[9px] px-2 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer transition-colors"
                  >
                    Gestante (TPP)
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const txt = `ADMITIDA EM ${bed.admissionDate || 'RECENTE'} DEVIDO QUADRO DE ABORTAMENTO INCOMPLETO. SUBMETIDA A CURETAGEM UTERINA SOB RAQUIANESTESIA.`;
                      updateField('hda', txt);
                      onShowToast('Modelo curetagem inserido!');
                    }}
                    className="text-[9px] px-2 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer transition-colors"
                  >
                    Curetagem
                  </button>
                </div>
              </div>

              {/* HD (Span 2) */}
              <div className="md:col-span-2">
                <div className="flex items-center justify-between mb-1">
                  <label className="text-[11px] font-bold text-slate-600 uppercase block">
                    HD (Hipótese Diagnóstica):
                  </label>
                  <div className="flex flex-wrap gap-1">
                    {['PEG PÓS PARTO + HELLP PARCIAL', 'PUERPÉRIO FISIOLÓGICO', 'GESTAÇÃO TÓPICA TPP', 'PIELONEFRITE AGUDA', 'ITU NA GESTAÇÃO', 'PRÉ-ECLÂMPSIA (PE)'].map((hd) => (
                      <button
                        key={hd}
                        type="button"
                        onClick={() => updateField('hdText', hd)}
                        className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer"
                      >
                        {hd.slice(0, 16)}...
                      </button>
                    ))}
                  </div>
                </div>
                <input
                  type="text"
                  value={bed.hdText ?? bed.diagnosis?.toUpperCase() ?? ''}
                  onChange={(e) => updateField('hdText', e.target.value)}
                  placeholder="Ex: PEG PÓS PARTO + HELLP PARCIAL"
                  className="w-full bg-white border border-slate-200 rounded-xl px-2.5 py-1.5 text-xs text-slate-800 font-bold focus:outline-none focus:border-purple-500"
                />
              </div>

              {/* Exames Complementares (Span 2) */}
              <div className="md:col-span-2">
                <div className="flex items-center justify-between mb-1">
                  <label className="text-[11px] font-bold text-slate-600 uppercase block">
                    EXAMES COMPLEMENTARES:
                  </label>
                  <button
                    type="button"
                    onClick={() =>
                      updateField(
                        'examesLabText',
                        `LAB 18/09/26: UREIA: 49| HB: 9,6| HT: 28,2| LEUCO: 12.710| PLAQ: 497.000| CREAT: 1,18| TGO: 27 | TGP: 33| EAS: LEUCO 7 HEMACIAS 15\nLAB 20/09/26: UREIA: 25| CREAT: 1| TGO: 30| TGP: 43| BILI T: 0,43 BILI D: 0,1| BILI IND: 0,33| LDH: 552| HB: 12,1| HT: 37,0| LEUCO: 12540| PLAQ: 677.0000| EAS: HEM: 462/ LEUCO: 389`
                      )
                    }
                    className="text-[10px] text-purple-700 hover:underline cursor-pointer"
                  >
                    Inserir Exames Modelo (18 e 20/09)
                  </button>
                </div>
                <textarea
                  rows={3}
                  value={bed.examesLabText ?? ''}
                  onChange={(e) => updateField('examesLabText', e.target.value)}
                  placeholder="LAB 18/09/26: UREIA: 49| HB: 9,6| HT: 28,2| LEUCO: 12.710| PLAQ: 497.000| CREAT: 1,18..."
                  className="w-full bg-white border border-slate-200 rounded-xl p-2 font-mono text-[11px] text-slate-800 focus:outline-none focus:border-purple-500"
                />
              </div>

              {/* CONDUTA (Span 2) */}
              <div className="md:col-span-2">
                <div className="flex items-center justify-between mb-1">
                  <label className="text-[11px] font-bold text-slate-600 uppercase block">
                    CONDUTA:
                  </label>
                  <div className="flex gap-1">
                    <button
                      type="button"
                      onClick={() => quickAppendConduta('SOLICITO LAB')}
                      className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer"
                    >
                      + Lab
                    </button>
                    <button
                      type="button"
                      onClick={() => quickAppendConduta('ALTA HOSPITALAR COM ORIENTAÇÕES')}
                      className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-emerald-200 text-emerald-700 hover:bg-emerald-50 cursor-pointer font-semibold"
                    >
                      + Alta c/ Orientações
                    </button>
                    <button
                      type="button"
                      onClick={() => quickAppendConduta('ATB - D2')}
                      className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 cursor-pointer"
                    >
                      + ATB
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        const atestPac = bed.data?.atestadoPaciente || bed.atestadoPaciente;
                        const dias = bed.data?.atestadoPacienteDias || bed.atestadoPacienteDias || '14 DIAS';
                        if (atestPac === 'licenca_maternidade') {
                          quickAppendConduta('LICENÇA MATERNIDADE (120 DIAS)');
                        } else {
                          quickAppendConduta(`ATESTADO MÉDICO (${dias.toUpperCase()})`);
                        }
                      }}
                      className="text-[9px] px-1.5 py-0.5 rounded bg-white border border-purple-200 text-purple-700 hover:bg-purple-50 cursor-pointer"
                    >
                      + Atestado
                    </button>
                  </div>
                </div>
                <textarea
                  rows={3}
                  value={bed.condutaText ?? ''}
                  onChange={(e) => updateField('condutaText', e.target.value)}
                  placeholder="SUPORTE CLÍNICO&#10;ATB - D2&#10;SOLICITO LAB&#10;AVALIAR ALTA"
                  className="w-full bg-white border border-slate-200 rounded-xl p-2 font-mono text-[11px] text-slate-800 focus:outline-none focus:border-purple-500 uppercase"
                />
              </div>
            </div>
          </div>
        )}

        {/* Text Area / Content Display */}
        <div className="mt-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-bold text-slate-700 flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5 text-purple-600" />
              Texto Formatado da Evolução Médica (Pronto para o Prontuário):
            </span>
            {isDirectEditing && (
              <span className="text-[11px] text-amber-700 bg-amber-50 px-2 py-0.5 rounded-md font-semibold border border-amber-200">
                Modo de Edição Livre Ativo
              </span>
            )}
          </div>

          {isDirectEditing ? (
            <textarea
              value={displayText}
              onChange={(e) => setCustomText(e.target.value)}
              rows={20}
              className="w-full bg-slate-900 text-slate-100 rounded-2xl p-4 font-mono text-xs leading-relaxed border border-purple-400 focus:outline-none focus:ring-2 focus:ring-purple-500/30 selection:bg-purple-600 selection:text-white"
            />
          ) : (
            <div className="bg-slate-900 text-slate-100 rounded-2xl p-5 font-mono text-xs sm:text-[13px] leading-relaxed border border-slate-800 whitespace-pre-wrap select-all shadow-inner print-area">
              {displayText}
            </div>
          )}
        </div>

        {/* Footer actions & guidance */}
        <div className="mt-4 pt-3 border-t border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs text-slate-500">
          <span className="flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>
              Formatado conforme o modelo padrão da maternidade com quebras de linhas e seções canônicas.
            </span>
          </span>

          <button
            onClick={onNavigateToDischarge}
            className="font-bold text-purple-700 hover:text-purple-800 hover:underline flex items-center gap-1.5 self-end sm:self-auto cursor-pointer"
          >
            <span>Ver Documentos de Alta & Receituário</span>
            <FileCheck className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};
